@PaymentGateway_HostAddress = http://localhost:5288

POST {{PaymentGateway_HostAddress}}/payments 
Content-Type: application/json

{
  "amount": 4200,
  "Currency": "USD"
  
} 

###

GET {{PaymentGateway_HostAddress}}/payments/194c2da3-40c9-4ea1-a9d3-081e8ed4bcfd

###
GET {{PaymentGateway_HostAddress}}/payments/00000000-0000-0000-0000-000000000000

###
GET {{PaymentGateway_HostAddress}}/payments