### 1. Создаем первый платеж (USD)
POST http://localhost:5288/payments
Content-Type: application/json

{
  "amount": 100.00,
  "currency": "USD"
}

### 2. Создаем второй платеж (EUR)
POST http://localhost:5288/payments
Content-Type: application/json

{
  "amount": 250.50,
  "currency": "EUR"
}

### 3. Создаем третий платеж (UZS)
POST http://localhost:5288/payments
Content-Type: application/json

{
  "amount": 50000.00,
  "currency": "UZS"
}

### 4. Создаем четвертый платеж (RUB)
POST http://localhost:5288/payments
Content-Type: application/json

{
  "amount": 1500.00,
  "currency": "RUB"
}

### ---------------------------------------------------
### ТЕСТЫ ПАГИНАЦИИИ И СОРТИРОВКИ
### ---------------------------------------------------

### A. Дефолтный запрос (все элементы)
GET http://localhost:5288/payments

### B. Страница 1, по 2 элемента 
GET http://localhost:5288/payments?page=1&pageSize=2

### C. Страница 2, по 2 элемента
GET http://localhost:5288/payments?page=2&pageSize=2